### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by CorreyL**
Hello @mukund109 

I'm making this PR in hopes to improve the `README.md` of your repository.

I noticed that users would have to scroll quite a bit to get to the bottom of the README due to large example images.

I've moved some of the example images to example/README.md to allow users to more easily access the rest of the README, as I noticed there are some important details after the `Examples` section, such as `Installation` and `Tutorial`. I've linked to `example/README.md` below the example I left in the `Example` section of the front-page `README.md`

In the interest of full transparency, this edit is for an assignment for a university technical writing course. A higher grade will be rewarded if PRs are approved. Please let me know if there are any issues with this PR that could be rectified, or any further additions I can make, in order to achieve an approval.

### CODE REVIEW

**Comment by mukund109** [comment]
Thanks for the suggestion @CorreyL
However, I see all examples as being critical in explaining the usefulness of the package. I think a better solution would be to have a table of contents at the beginning.
So if you can create a table of contents without moving the examples around, I will approve your PR.

**Comment by CorreyL** [comment]
Concerns addressed in commit 2573871

I'm not super familiar with the restrictions regarding `Python 2.7.x` and `Python 3.x`, but I was wondering if it might be worth mentioning in the `Installation` section regarding which `Python` is necessary to run this application? Unless it works with both, then disregard this message. =P

**Comment by CorreyL** [comment]
Pinging this PR in hopes to make any necessary changes for an approval, as this assignment is due tonight.

**Comment by cyonghui81** [comment]
What could be likely reasons that wm.plot shows up nothing in jupyter notebook. On my home laptop it is okay but on my dev laptop which has no internet it doesn't work.

**Comment by mukund109** [comment]
> What could be likely reasons that wm.plot shows up nothing in jupyter notebook. On my home laptop it is okay but on my dev laptop which has no internet it doesn't work.

Hi, try checking if [Plotly](https://plot.ly/) works in **offline mode** on your work laptop. If it doesn't, then that could explain why wm.plot isn't working, and we could try diagnosing the problem further.

**Pull request merged**
